### ISSUE TITLE
Running it with actix_rt

### ISSUE THREAD

**Issue by Selyatin** [serenity-rs/serenity#1320]
How can I achieve this?

**Comment by Lakelezz** [comment]
I do know the actix runtime uses tokio underneath, are you encountering a specific error?

**Comment by Selyatin** [comment]
It panics whenever I try to run a serenity client. I've decided to use routerify, which is just a wrapper around hyper and it works pretty fine for now. I don't know what the issue was and I don't have the error message right now, but if I remember right it might've been related to websockets or rustls.

@Lakelezz

**Comment by Lakelezz** [comment]
I do assume that actix-rt is unable to do such at this point in time.

**Comment by peppizza** [comment]
It could be because the current stable release of actix_rt uses tokio 0.2, so I would recommend using the most recent beta version of actix_rt which uses tokio 1

**Comment by Selyatin** [comment]
I've tried it with the beta version, still the same, so I just used routerify instead.

**Comment by adumbidiot** [comment]
I can't reproduce the issue. What was your setup? Here's what I used:
main.rs:
```rust
use actix_rt::{Arbiter, System};
use serenity::{
    async_trait,
    model::{channel::Message, gateway::Ready},
    prelude::*,
};
use std::env;

struct Handler;

#[async_trait]
impl EventHandler for Handler {
    async fn message(&self, ctx: Context, msg: Message) {
        if msg.content == "!ping" {
            if let Err(why) = msg.channel_id.say(&ctx.http, "Pong!").await {
                println!("Error sending message: {:?}", why);
            }
        }
    }

    async fn ready(&self, _: Context, ready: Ready) {
        println!("{} is connected!", ready.user.name);
    }
}

fn main() {
    let token = env::var("DISCORD_TOKEN").expect("Expected a token in the environment");
    let _ = System::new();

    let arbiter = Arbiter::new();
    arbiter.spawn(async move {
        let mut client = Client::builder(&token)
            .event_handler(Handler)
            .await
            .expect("Err creating client");

        if let Err(why) = client.start().await {
            println!("Client error: {:?}", why);
        }
    });

    arbiter.join().unwrap();
}
```
Cargo.toml:
```toml
[package]
name = "serenity-issue-1320"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-rt = "2.2.0"
serenity = { version = "0.10.8", default-features = false, features = [ "client", "gateway", "rustls_backend", "model" ] }
```

**Comment by Selyatin** [comment]
I have not used an arbiter I've just spawned a new task normally as you would in tokio runtime

**Comment by adumbidiot** [comment]
Oh right you are trying to build a web app. Well modifying one of their examples, I can reproduce the panic issue on the stable version, but the beta version works fine as it uses tokio 1.0. What was your setup for the beta version of actix? My setup:
main.rs:
```rust
use actix_web::{get, web, App, HttpServer, Responder};
use serenity::{
    async_trait,
    model::{channel::Message, gateway::Ready},
    prelude::*,
};
use std::env;

struct Handler;

#[async_trait]
impl EventHandler for Handler {
    async fn message(&self, ctx: Context, msg: Message) {
        if msg.content == "!ping" {
            if let Err(why) = msg.channel_id.say(&ctx.http, "Pong!").await {
                println!("Error sending message: {:?}", why);
            }
        }
    }

    async fn ready(&self, _: Context, ready: Ready) {
        println!("{} is connected!", ready.user.name);
    }
}

#[get("/{id}/{name}/index.html")]
async fn index(path: web::Path<(u32, String)>) -> impl Responder {
    let (id, name) = path.into_inner();
    format!("Hello {}! id:{}", name, id)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let token = env::var("DISCORD_TOKEN").expect("Expected a token in the environment");
    tokio::spawn(async move {
        let mut client = Client::builder(&token)
            .event_handler(Handler)
            .await
            .expect("Err creating client");

        if let Err(why) = client.start().await {
            println!("Client error: {:?}", why);
        }
    });

    HttpServer::new(|| App::new().service(index))
        .bind("127.0.0.1:8080")?
        .run()
        .await
}
```
Cargo.toml:
```toml
[package]
name = "serenity-issue-1320"
version = "0.1.0"
edition = "2018"

[dependencies]
serenity = { version = "0.10.8", default-features = false, features = [ "client", "gateway", "rustls_backend", "model" ] }
# actix-web = "3.3.2"
actix-web = "4.0.0-beta.5"
tokio = "1.7.0"

````
