### ISSUE TITLE
Some event fails to deserialize, obtaining a `DateTime<Utc>` string rather than an integer

### ISSUE THREAD

**Issue by vicky5124** [serenity-rs/serenity#1431]
Been getting this warn trace log since the middle of yesterday, notifying of an error deserializing an event that used to provide an integer but now provides a `DateTime<Utc>` String.
This is likely due to the API v9 update that happened on the `current` branch, and should get fixed before a crates.io release happens.

`Jul 06 22:16:10.290  WARN run:recv_event:handle_event{event=Err(Json(Error("invalid type: string \"2021-07-06T21:16:10.208870+00:00\", expected u64", line: 0, column: 0)))}: serenity::gateway::shard: [Shard [0, 1]] Unhandled error: Json(Error("invalid type: string \"2021-07-06T21:16:10.208870+00:00\", expected u64", line: 0, column: 0))`

```toml
[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "current"
```
With all intents + privileged.
