### ISSUE TITLE
Pre-existing categories are not present in Cache

### ISSUE THREAD

**Issue by tiritto** [serenity-rs/serenity#1511]
**Current behavior:**
Cache does not contain any information about pre-existing categories on the server.
This issue exists in both `current` and `next` branch. 

**Expected behavior:**
Cache is being populated with all pre-existing categories on startup.

**Source code that can be used to replicate the issue on `next` branch:**
```rust
use serenity::{
    async_trait,
    model::{channel::Message, gateway::Ready, id::GuildId, guild::Member},
    prelude::*,
    client::bridge::gateway::GatewayIntents,
    http::CacheHttp,
};

struct Handler;

#[async_trait]
impl EventHandler for Handler {
    async fn message(&self, ctx: Context, msg: Message) {
        let categories = ctx.cache.categories();
        println!("{} elements", categories.clone().into_iter().count()); // RETURNS: "0 elements"

        if categories.is_empty() {
            println!("'categories' is empty!"); // <- Gets triggered
        }

        let current_category = msg.category_id(ctx.cache);
        match current_category {
            None => println!("This channel has no category!"), // <- Gets triggered
            Some(id) => println!("This category has ID: {}", id.as_u64())
        }
    }
}

#[tokio::main]
async fn main() {
    let token = String::from("XYZABC");
    let mut client =
        Client::builder(&token)
            .intents(GatewayIntents::GUILDS | GatewayIntents::GUILD_MEMBERS | GatewayIntents::GUILD_MESSAGES)
            .event_handler(Handler)
            .await
            .expect("Err creating client");
    if let Err(why) = client.start().await {
        println!("Client error: {:?}", why);
    }
}
```

```toml
[package]
name = "rust_bot"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
default-features = false
features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "rustls_backend"]
```
