### ISSUE TITLE
Command Framework enabled but not provided error. 

### ISSUE THREAD

**Issue by RylanYancey** [serenity-rs/serenity#1622]
## What I've done

 I've set up the example project 1 (ping bot)

## The Issue I'm Having

This error:
> `thread 'main' panicked at 'The 'framework'-feature is enabled (it's on by default), but no framework was provided.
If you don't want to use the command framework, disable default features and specify all features you want to use.', /home/rylan/.cargo/registry/src/github.com-1ecc6299db9ec823/serenity-0.10.9/src/client/mod.rs:355:18
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace`

I think that the way I'm adding my dependencies is wrong.
> See the Cargo.toml file: 
```toml
[package]
name = "score_keeper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.9"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
```

## What I think needs to be done

I think that I need to disable the default configuration of the dependency and manually put in what I want to include within Serenity.  However, I am not familiar enough with Rust and TOML to do this. 

## Conclusion

Any help on the [dependencies] list is very appreciated.  If anybody has any advice on how I can figure out this information for myself in the future I will be very grateful to hear it.

**Comment by arqunis** [comment]
To fix this, all you have to do is disable the default features and specify the features you need manually. Since you are basing the project off of example 1, you do not need many features:
```toml
[dependencies]
serenity = { version = "0.10.9", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
```

**Comment by RylanYancey** [comment]
@acdenisSK 

Thanks for the reply acdenis, 

Is this standard format for importing crates? is it like this for all/most crates? how do you know which ones you need?

**Comment by arqunis** [comment]
> Is this standard format for importing crates? Is it like this for all/most crates?

Yes. All dependencies are either defined collectively under the `[dependencies]` table (like above), or individually like so:
```toml
[dependencies.<crate-name>]
version = "<version>"
# other fields like `features = [....]`
```

Some crates may only be used on certain operating systems, such as Windows. For this, you may use the above `[dependencies.<crate-name>]` format and specify between `dependencies` and the crate name the condition upon which to install the crate. For example, to only install `winapi` when building on Windows:

```toml
[dependencies.'cfg(windows)'.winapi]
version = "0.3.9"
# ....
```

Sometimes, a crate may only be used in development (that is, it's only useful for developers of the crate, during testing for instance). In such a case, the `[dev-dependencies]` table is more appropriate, where the syntax and rules are the same as `[dependencies]`. Or if a crate is used for building the crate (such as for compiling C/C++ code), it should be put under `[build-dependencies]`.

You may find the full documentation for the `Cargo.toml` format in the [Cargo Book](https://doc.rust-lang.org/cargo/reference/manifest.html).

> How do you know which ones you need?

¯\\\_(ツ)\_/¯

A crate, specifically a library crate, is just reusable code. It is designed to be used by other crates. Whether or not you decide to depend on it is entirely on you. For what it's worth, you could even write the behaviour a crate provides yourself.

Most of the time, however, you do not want to do that. This is for several reasons, including:
- Time. You may not have the time or want to bother to write the code yourself and instead should/must focus on features and behaviour specific to the application. 
- Code quality. In the case you do write the code, it may not be fast, or be at worst buggy. Crates are not excluded from this, as they also can contain bad code. But their purpose is to be used by others, so a lot of the time, extra care will be put on their code.
- Feature parity. Your code may also not implement and handle all features and cases that it should. Again, crates are not exempt from this, but they're more likely to be complete than your code.
- Consensus. Generic interfaces in Rust are implemented with traits, which are a great way to deduplicate code and share behaviour. This only works if you work together, however. If you want a function to accept any type as long as they implement a certain trait (or a group of traits), you need to ensure that you and the function's consumers use the same version of the trait. A great example of this is [`serde`](https://docs.rs/serde), which is a serialisation/deserialisation framework. It allows you convert data to and from a format (like json) without depending on any specific format (i.e. besides json, you may convert to xml, toml, yaml, and many more). The only way this framework works is by sharing interfaces between types and serializers/deserializers. Types that can be serialized/deserialized implement the `Serialize` and `Deserialize` traits, while the types that do the actual conversion implement `Serializer` and `Deserializer` (like [`serde_json`](https://docs.rs/serde_json) for serializing/deserializing to/from json).

If you want to find out crates to use, you may search through https://crates.io or https://lib.rs. Alternatively, you may stumble upon crates on blogs and sites such as https://reddit.com/r/rust and https://this-week-in-rust.org.

And if you want to make it easier to consume crates, you should consider installing [`cargo-edit`](https://github.com/killercup/cargo-edit). It's a set of command-line tools for managing dependencies without editing `Cargo.toml` directly.
