### ISSUE TITLE
Http.send_message panics with 'expected object'

### ISSUE THREAD

**Issue by PastelStoic** [serenity-rs/serenity#2417]
I followed the slash command example to the letter, but wanted to be able to send messages once every so often - however, the seemingly-innocent send_message apparently has some issues.

To replicate: clone e14_slash_commands and add the following two lines at the end of the ready handler:
```rust
let msg = json!("message"); // or any other string Value
ctx.http.send_message(1094600368203243633, &msg).await.ok();
```
You should (assuming my computer isn't the one at fault) get `thread 'tokio-runtime-worker' panicked at 'expected object'`.

Enviroment:
rustc 1.69
Windows 10

Dependencies:
```toml
[dependencies]
rand = "0.8.5"
serenity = { version ="0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"
poise = "0.5.2"
```
