### ISSUE TITLE
Guild missing in cache for no apparent reason.

### ISSUE THREAD

**Issue by LuckyMika** [serenity-rs/serenity#2590]
TLDR;
When trying to get a members permissions from a text message they sent, serenity always fails with `Model(GuildNotFound)`.
## Clarifications
The `cache` feature is enabled.
The `GUILD_MEMBERS`, `MESSAGE_CONTENT`, `GUILD_MESSAGES` and `GUILDS` intents are enabled.
All of the intents are turned on in the developer page of the application
The bot is in exactly 1 server

## The issues
When receiving a message from a guild member, I have tried to get their permissions with the following methods:
- Using the `member` field to get it's `permissions` field directly.
- Querying the member via the `member` function 
    - getting its `permission` field
    - querying the permissions via the `permissions` function
- Try to get the member via the guild's `member` function
    - getting its `permission` field
    - querying the permissions via the `permissions` function

## The error
All of the above have failed with an error stating that the guild cannot be found in the cache.
It happens when trying to `unwrap()` the permissions

## Example code
Here is some example code that I have made to confirm all of my tests
The code actually **fails**, particularly when fetching the guild, as it was not found in the cache. This makes no sense for me, since the cache feature is enabled, the message was sent in a guild and I have been testing this with the bot running for around 20 minutes so it couldn't even be a "cold" cache.
```rust
use serenity::{client::Context, model::channel::Message};

pub async fn test(ctx: Context, msg: Message) {
    println!("{:?}", msg.guild_id.expect("Message was not sent in a guild"));

    println!("{:?}", msg.clone().member.unwrap().permissions);
    println!("{:?}", msg.clone().member(&ctx).await.unwrap().permissions);
    println!("{:?}", msg.member(&ctx).await.unwrap().permissions(&ctx));
    println!("{:?}", msg.guild(&ctx).expect("Failed to fetch guild").member(&ctx, &msg.author.id).await.expect("Failed to fetch member").permissions);
    println!("{:?}", msg.guild(&ctx).expect("Failed to fetch guild").member(&ctx, &msg.author.id).await.expect("Failed to fetch member").permissions(&ctx));

    msg.reply(&ctx, "Successfully ran tests").await.expect("Failed to send message");
}
```
Additionally, here is my Cargo.toml:
```toml
[package]
name = "rust_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { default-features = false, version = "0.11", features = ["builder", "cache", "collector", "client", "model", "time", "http", "utils", "rustls_backend"] }
tokio = { version = "1.21.2", features = ["full"] }
dotenv = "0.15.0"
serde = "1.0.192"
serde_json = "1.0.108"
```
