### ISSUE TITLE
Unresolved import for serenity::utils::CreateQuickModal v0.12.2

### ISSUE THREAD

**Issue by Matheuswells** [serenity-rs/serenity#2979]
src/commands./modal.rs
```rust
use serenity::builder::*;
use serenity::model::prelude::*;
use serenity::prelude::*;

pub async fn run(ctx: &Context, interaction: &CommandInteraction) -> Result<(), serenity::Error> {
    let modal = CreateQuickModal::new("About you")
        .timeout(std::time::Duration::from_secs(600))
        .short_field("First name")
        .short_field("Last name")
        .paragraph_field("Hobbies and interests");
    let response = interaction.quick_modal(ctx, modal).await?.unwrap();

    let inputs = response.inputs;
    let (first_name, last_name, hobbies) = (&inputs[0], &inputs[1], &inputs[2]);

    response
        .interaction
        .create_response(
            ctx,
            CreateInteractionResponse::Message(CreateInteractionResponseMessage::new().content(
                format!("**Name**: {first_name} {last_name}\n\nHobbies and interests: {hobbies}"),
            )),
        )
        .await?;
    Ok(())
}

pub fn register() -> CreateCommand {
    CreateCommand::new("modal").description("Asks some details about you")
}

```

![image](https://github.com/user-attachments/assets/b8f0e589-8b70-4996-89d4-ccd37e5b205a)

project/Cargo.toml
```toml
[package]
name = "*******"
version = "0.1.0"
edition = "2021"
authors = ["******<*****@*****.***>"]

[dependencies]
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
serenity = { default-features = false, features = [
    "client",
    "gateway",
    "model",
    "rustls_backend",
    "framework",
    "standard_framework",
], version = "0.12.2" }

dotenvy = "0.15"

```
