### ISSUE TITLE
Error decoding a ChannelId with serde's arbitrary_precision feature

### ISSUE THREAD

**Issue by fenhl** [serenity-rs/serenity#527]
Not sure if this is a serenity bug or a serde bug. It doesn't happen with a plain `u64` but it also doesn't happen without the `arbitrary_precision` feature. Minimal test case:

# Cargo.toml

```toml
[package]
name = "example"
version = "0.1.0"
edition = "2018"

[dependencies]
serenity = "=0.5.13"

[dependencies.serde_json]
version = "=1.0.39"
features = ["arbitrary_precision"]
```

# main.rs

```rust
use serenity::model::id::ChannelId;

fn main() -> serde_json::Result<()> {
    serde_json::from_str::<ChannelId>("535157675466686464")?;      
    Ok(())
}
```

# Output

```
Error: Error("invalid type: map, expected identifier", line: 1, column: 18)
```
